services:
  - type: web
    name: payfichain
    env: go
    plan: free

    envVars:
      - key: GO_VERSION
        value: 1.22.2

    buildCommand: |
      go mod tidy
      make build

    startCommand: |
      ./build/gaiad start --minimum-gas-prices=0.025stake